### ISSUE TITLE
1.20.4 Support

### ISSUE THREAD

**Issue by Opa-Jones** [Navoei/CustomDiscs#59]
When the plugin is installed on 1.20.4 it gives an error in the chat.

|An error has occurred while trying to play this disc.|

I was hoping there is either a fix for this or that the plugin could add 1.20.4 support.

**Comment by notqtcris** [comment]
bump

**Comment by Navoei** [comment]
Can you send the stack trace?

**Comment by Opa-Jones** [comment]
> Can you send the stack trace?

I'm on vacation ATM. I return back home saturday. Won't beable to until then.

**Comment by Timtaran** [comment]
1.20.4 works fine

**Comment by Timtaran** [comment]
Did you install last version of ProtocolLib? https://ci.dmulloy2.net/job/ProtocolLib/

**Comment by Opa-Jones** [comment]
> Can you send the stack trace?

Sorry forgot about this.

this is the cosnole error it prins
https://pastebin.com/LLM0cwPy

**Comment by NathanBanner** [comment]
I also can't load it on Spigot 1.20.4
But I get this instead:
26.02 02:27:35 [Server] Server thread/[INFO] [CustomDiscs] Enabling CustomDiscs v2.5.1
26.02 02:27:35 [Server] Server thread/[INFO] Successfully registered CustomDiscs plugin
26.02 02:27:35 [Server] Server thread/[ERROR] Error occurred while enabling CustomDiscs v2.5.1 (Is it up to date?)
26.02 02:27:35 [Server] [INFO] java.lang.NoClassDefFoundError: net/kyori/adventure/text/format/TextColor
26.02 02:27:35 [Server] [INFO] at me.Navoei.customdiscsplugin.CustomDiscs.onEnable(CustomDiscs.java:69) ~[?:?]
26.02 02:27:35 [Server] [INFO] at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[spigot-api-1.20.4-R0.1-SNAPSHOT.jar:?]
26.02 02:27:35 [Server] [INFO] at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.20.4-R0.1-SNAPSHOT.jar:?]
26.02 02:27:35 [Server] [INFO] at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-api-1.20.4-R0.1-SNAPSHOT.jar:?]
26.02 02:27:35 [Server] [INFO] at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:541) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4052-Spigot-e9ec548-98b6c1a]
26.02 02:27:35 [Server] [INFO] at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:455) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4052-Spigot-e9ec548-98b6c1a]
26.02 02:27:35 [Server] [INFO] at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:623) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4052-Spigot-e9ec548-98b6c1a]
26.02 02:27:35 [Server] [INFO] at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:409) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4052-Spigot-e9ec548-98b6c1a]
26.02 02:27:35 [Server] [INFO] at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:250) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4052-Spigot-e9ec548-98b6c1a]
26.02 02:27:35 [Server] [INFO] at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1000) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4052-Spigot-e9ec548-98b6c1a]
26.02 02:27:35 [Server] [INFO] at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4052-Spigot-e9ec548-98b6c1a]
26.02 02:27:35 [Server] [INFO] at java.lang.Thread.run(Thread.java:833) ~[?:?]
26.02 02:27:35 [Server] [INFO] Caused by: java.lang.ClassNotFoundException: net.kyori.adventure.text.format.TextColor
26.02 02:27:35 [Server] [INFO] at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:160) ~[spigot-api-1.20.4-R0.1-SNAPSHOT.jar:?]
26.02 02:27:35 [Server] [INFO] at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:112) ~[spigot-api-1.20.4-R0.1-SNAPSHOT.jar:?]
26.02 02:27:35 [Server] [INFO] at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
26.02 02:27:35 [Server] [INFO] ... 12 more

**Comment by DaddyRobLIVE** [comment]
update? is this working fine for 1.20.4?

**Comment by DaddyRobLIVE** [comment]
Hi please update to 1.20.4 the song doesn't stop if you remove the disc from the jukebox :/

**Comment by lowercasebtw** [comment]
1.20.6 support pls, in like 1 1/2 weeks, 1.21 will also be out

**Comment by lowercasebtw** [comment]
I use purpur

**Comment by lowercasebtw** [comment]
I use purpur, and it doesn't work.

**Comment by lowercasebtw** [comment]
![image](https://github.com/Navoei/CustomDiscs/assets/126462578/a55b9bbf-0d31-444f-b8d7-9ee85841c105)

**Comment by Navoei** [comment]
Once 1.21 is out I will work on an update! I apologize for the lack of updates or support.

**Comment by lowercasebtw** [comment]
I tried updating it myself and got it to not be red ingame when doing /pl

but the music doesnt play cause it can't find MpegAudioFileReader (ClassNotDef)

**Comment by lowercasebtw** [comment]
I also had to add a try block in onServerStart but idk it thats req or not cuz I also after updated protocollib (built from their github)

**Comment by lowercasebtw** [comment]
```[11:38:59 WARN]: Exception in thread "AudioPlayerThread" java.lang.NoClassDefFoundError: javazoom/spi/mpeg/sampled/file/MpegAudioFileReader
[11:38:59 WARN]:        at custom-discs-2.6.jar//me.Navoei.customdiscsplugin.PlayerManager.convertFormat(PlayerManager.java:131)
[11:38:59 WARN]:        at custom-discs-2.6.jar//me.Navoei.customdiscsplugin.PlayerManager.readSoundFile(PlayerManager.java:121)
[11:38:59 WARN]:        at custom-discs-2.6.jar//me.Navoei.customdiscsplugin.PlayerManager.playChannel(PlayerManager.java:105)
[11:38:59 WARN]:        at custom-discs-2.6.jar//me.Navoei.customdiscsplugin.PlayerManager.lambda$playLocationalAudio$4(PlayerManager.java:73)
[11:38:59 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[11:38:59 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[11:38:59 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[11:38:59 WARN]: Caused by: java.lang.ClassNotFoundException: javazoom.spi.mpeg.sampled.file.MpegAudioFileReader
[11:38:59 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:197)
[11:38:59 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164)
[11:38:59 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
[11:38:59 WARN]:        ... 7 more
[11:39:03 WARN]: Exception in thread "AudioPlayerThread" java.lang.NoClassDefFoundError: javazoom/spi/mpeg/sampled/file/MpegAudioFileReader
[11:39:03 WARN]:        at custom-discs-2.6.jar//me.Navoei.customdiscsplugin.PlayerManager.convertFormat(PlayerManager.java:131)
[11:39:03 WARN]:        at custom-discs-2.6.jar//me.Navoei.customdiscsplugin.PlayerManager.readSoundFile(PlayerManager.java:121)
[11:39:03 WARN]:        at custom-discs-2.6.jar//me.Navoei.customdiscsplugin.PlayerManager.playChannel(PlayerManager.java:105)
[11:39:03 WARN]:        at custom-discs-2.6.jar//me.Navoei.customdiscsplugin.PlayerManager.lambda$playLocationalAudio$4(PlayerManager.java:73)
[11:39:03 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[11:39:03 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[11:39:03 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[11:39:03 WARN]: Caused by: java.lang.ClassNotFoundException: javazoom.spi.mpeg.sampled.file.MpegAudioFileReader
[11:39:03 WARN]:        ... 7 more```

**Comment by Navoei** [comment]
Currently working on a 1.20.4 update since it is highly requested.

**Comment by Navoei** [comment]
That error is caused due to not shadowing the jar.

**Comment by Navoei** [comment]
Plugin should work in 1.20.6? I havent tested it yet so if anyone wants to then please do and report any bugs to me.

**Comment by lowercasebtw** [comment]
![image](https://github.com/Navoei/CustomDiscs/assets/126462578/dca5ed83-4544-403d-aa82-2131c7ac0c54)

**Comment by NathanBanner** [comment]
While it's not showing any errors now and it seems to have downloaded the file successfully, I tried setting a music disc to the custom file but it's not playing anything from the jukebox. I have ensured the file on my server is, indeed, a working mp3
